name: api
endpoint: /api
source_config_names:
  - user.yaml
  - product.yaml
  - order.yaml
mesh:
  additionalTypeDefs: |
    type Order {
      id: Int!
      user_id: Int!
      product_id: Int!
      user: UsersListItem!
      product: ProductsListItem!
    }
    extend type Query {
      orders: [Order]
    }
  additionalResolvers:
    - ./resolvers/orders.js
  transforms:
    - cache:
        - field: Query.*
