hostname: localhost
listen_port: 8080
pool_size: 1
secret: ''
apis_path: './config/apis'
sources_path: './config/sources'
middleware_path: ''
use_dashboard_configs: false
dashboard_config:
  connection_string: http://localhost:3030/
enable_control_api: false
control_api_config:
  endpoint: /control_api
log_level: debug
log_format: text
redis_connection_string: redis://localhost:6379/
