swagger: '2.0'
paths:
  /users:
    get:
      summary: Returns a list of users.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: Arthur Dent
  /users/{id}:
    get:
      summary: Returns a user by id.
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: The ID of a user
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 1
              name:
                type: string
                example: Arthur Dent
