name: order
handler:
  jsonSchema:
    baseUrl: http://localhost:3003
    operations:
      - type: Query
        field: getOrders
        path: /orders
        method: GET
        responseSchema: ./schemas/orders.json
